### PR TITLE
Privacy

### PR DESCRIPTION
**Pull request by egocious**
https://egocious.github.io/egougwu/

Submission for private policy page

### CODE REVIEW

**Comment by Joshuafolorunsho** [comment]
Good job Ego, checked your work and I see you have done a very great job so far however, there is still one thing missing. The mobile  view

Take a look at how it looks on mobile
screencapture-egocious-github-io-egougwu-2019-10-23-01_14_23

**Comment by Joshuafolorunsho** [comment]
Good job Ego, checked your work and I see you have done a very good job however, there is still one thing missing. The mobile view

Take a look at how it looks on mobile

egocious

**Comment by Joshuafolorunsho** [comment]
If you noticed, you will see that the navbar is no longer complete, this footer goes missing when on small screens
image

Also take a look at the footer also on iPhone 6, not so good
image

**Comment by Eronmmer** [comment]
Please take care of responsiveness and reopen the PR when you're done

**Pull request closed without merging**
